import type { Catalogue, MachineDefinition } from "@isomill/schema";
import {
  assertHttpsUrl,
  assertSafeToken,
  catalogue as defaultCatalogue,
  getApplication,
  getOs,
  getTarget,
  shouldDropDistroFirefox,
} from "@isomill/catalogue";
import { assertKickstartSafety, osKeyOf, prepareDefinition } from "./common.js";

function fedoraLocale(definition: MachineDefinition, cat: Catalogue) {
  const os = getOs(definition, cat);
  const lang = os.locales.languages.find((l) => l.id === definition.locale.language)!;
  const kb = os.locales.keyboards.find((k) => k.id === definition.locale.keyboard)!;
  return { lang: lang.fedoraLang, keymap: kb.fedoraKeymap, timezone: definition.locale.timezone };
}

export function generateKickstart(
  input: MachineDefinition,
  cat: Catalogue = defaultCatalogue,
): string {
  const definition = prepareDefinition(input, cat);
  const loc = fedoraLocale(definition, cat);
  const packages = new Set<string>(["@^workstation-product-environment"]);
  const exclusions = new Set<string>();
  const repos: string[] = [];
  const npmPkgs: string[] = [];
  const units = new Set<string>();

  if (shouldDropDistroFirefox(definition, cat)) {
    exclusions.add("-firefox");
  }

  for (const id of definition.applications ?? []) {
    const app = getApplication(id, cat);
    const target = getTarget(app, definition);
    if (!target) continue;
    if (target.sourceClass === "npm") {
      if (!target.npmPackage) {
        throw new Error(`npm app ${id} missing npmPackage`);
      }
      assertSafeToken(target.npmPackage, "npm package");
      npmPkgs.push(target.npmPackage);
      continue;
    }
    for (const pkg of target.packages) {
      assertSafeToken(pkg, "package");
      packages.add(pkg);
    }
    if (target.sourceClass === "vendor" && target.vendor) {
      assertHttpsUrl(target.vendor.repoUrl.replaceAll("{arch}", "x86_64"), "repo");
      assertHttpsUrl(target.vendor.keyUrl, "key");
      const name = id.replace(/[^a-z0-9]/g, "");
      const repoUrl = target.vendor.repoUrl.replaceAll(
        "{arch}",
        definition.os.architecture,
      );
      repos.push(
        `repo --name=${name} --baseurl=${repoUrl} --gpgcheck=1 --gpgkey=${target.vendor.keyUrl}`,
      );
    }
    for (const unit of target.units ?? []) {
      assertSafeToken(unit, "unit");
      units.add(unit);
    }
  }

  for (const sid of definition.services ?? []) {
    const svc = cat.services.find((s) => s.id === sid);
    const t = svc?.targets[osKeyOf(definition)];
    for (const pkg of t?.packages ?? []) {
      assertSafeToken(pkg, "package");
      packages.add(pkg);
    }
    for (const unit of t?.units ?? []) {
      assertSafeToken(unit, "unit");
      units.add(unit);
    }
  }

  const lines: string[] = [
    "# Generated by isomill. Do not edit by hand.",
    "# Based on official Fedora installer media. Not a Fedora remix and not endorsed by the Fedora Project.",
    "# Identity and storage remain in Anaconda. This file never sets users, passwords, or disk layout.",
    "",
    `lang ${loc.lang}`,
    `keyboard --vckeymap=${loc.keymap}`,
    `timezone ${loc.timezone} --utc`,
    "graphical",
    "",
  ];

  if (repos.length) {
    lines.push("# Allowlisted first-party vendor repositories (URLs from the isomill catalogue).");
    lines.push(...repos, "");
  }

  if (units.size) {
    const enabled = [...units].map((u) => u.replace(/\.service$/, "")).join(",");
    lines.push(`services --enabled=${enabled}`, "");
  }

  lines.push("%packages");
  for (const pkg of [...packages].sort()) {
    lines.push(pkg);
  }
  for (const pkg of [...exclusions].sort()) {
    lines.push(pkg);
  }
  lines.push("%end", "");

  lines.push("%post --nochroot --erroronfail");
  lines.push("set -euo pipefail");
  lines.push("mkdir -p /mnt/sysimage/etc/isomill");
  lines.push(
    "if [ -d /run/install/repo/isomill ]; then cp -a /run/install/repo/isomill/. /mnt/sysimage/etc/isomill/; fi",
  );
  lines.push("%end", "");

  lines.push("%post --erroronfail");
  lines.push("set -euo pipefail");
  if (npmPkgs.length) {
    lines.push("# npm allowlist — not distro-signed. --ignore-scripts is mandatory.");
    for (const pkg of npmPkgs) {
      lines.push(`npm install -g --ignore-scripts ${pkg}`);
    }
  }
  for (const unit of units) {
    lines.push(`systemctl enable ${unit}`);
  }
  lines.push("%end");
  lines.push("");

  const ks = lines.join("\n");
  assertKickstartSafety(ks);
  return ks;
}
